url: "https://Prueba2.github.io" 
baseurl: "/"

# Site settings
title: De-stress ChatBot
email: malttz15@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
#stack-overflow
people:
- name: Mario Rosas Otero
  pic: Mario.jpeg
  position: Co-founder
  social:
    - title: twitter
      url: https://twitter.com/JMireles_
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/josemirelesq/

- name: Natalia Sanchez
  pic: Natalia.jpeg
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Maricarmen Salas
  pic: Maricarmen.jpeg
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Andrea Garibay
  pic: Andrea.png
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ClubesCienciaMx
  - title: facebook
    url: https://www.facebook.com/clubesdecienciamx
  - title: youtube
    url: https://www.youtube.com/user/ClubesDeCienciaMx
  - title: github
    url: https://github.com/Mariuki/Prueba2

# Build settings
markdown: kramdown
permalink: pretty
